/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package moe.kadosawa.aoc

fun input(filename: String) = {}::class.java.classLoader
    ?.getResourceAsStream(filename)
    ?.reader()

fun main() {
    val m = moe.kadosawa.aoc.day3.Main()
    m.run()
}
